{% set name = "cmaes" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6aab41eee2f38bf917560a7e7d1ba0060632cd44cdf7ac2a10704da994624182

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=61
  run:
    - python
    - numpy

test:
  source_files:
    - tests
  imports:
    - cmaes
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest
    - hypothesis

about:
  home: https://github.com/CyberAgentAILab/cmaes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
  description: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
  dev_url: https://github.com/CyberAgentAILab/cmaes
  doc_url: https://github.com/CyberAgentAILab/cmaes

extra:
  recipe-maintainers:
    - nomuramasahir0
    - c-bata
